name: Build tagged container

on:
  push:
    branches: [ prod ]
    tags:
      - 'v*'
jobs:
  build-container:
    name: Build and Publish to Azure Container Registry
    runs-on: ubuntu-latest
    env:
      SVC_NAME: fineract-svc
      ACR_NAME: epayprodregistry.azurecr.io

    steps:
      - uses: actions/checkout@v2

      - name: Get the tag name
        run: echo "TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: Azure/get-keyvault-secrets@v1.2
        with:
          keyvault: "monex-kv"
          secrets: 'ACR-USERNAME, ACR-PASSWORD'
        id: getAzSecret

      - name: Azure Container Registry Login
        uses: Azure/docker-login@v1
        with:
          login-server: epayprodregistry.azurecr.io
          username: ${{ steps.getAzSecret.outputs.ACR-USERNAME }}
          password: ${{ steps.getAzSecret.outputs.ACR-PASSWORD }}

      - name: Build Container image
        run: docker build -t ${ACR_NAME}/${SVC_NAME}:${{ env.TAG }} .

      - name: Publish Docker image
        run: docker push ${ACR_NAME}/${SVC_NAME}:${{ env.TAG }}